version: "3.4"
services:
  nginx:
    image: "nlwkobe30/complex-nginx"
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"
  client:
    image: "nlwkobe30/complex-client"
    hostname: client
    mem_limit: 128m
  api:
    image: "nlwkobe30/complex-api"
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
  worker:
    image: "nlwkobe30/complex-worker"
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
