version: "3.4"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ~/project/complex/client:/app
    environment:
      - WDS_SOCKET_PORT=0
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ~/project/complex/server:/app
    environment:
      # variable not give name -> take from computer
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=password
      - PG_PORT=5432
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ~/project/complex/worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
