name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: build test image and run test
        run: |
          docker build -t react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true react-test npm run test

      - name: build production images
        run: |
          docker build -t nlwkobe30/complex-nginx ./nginx
          docker build -t nlwkobe30/complex-client ./client
          docker build -t nlwkobe30/complex-server ./server
          docker build -t nlwkobe30/complex-worker ./worker

      - name: push docker hub
        run: |
          docker push nlwkobe30/complex-nginx
          docker push nlwkobe30/complex-client
          docker push nlwkobe30/complex-server
          docker push nlwkobe30/complex-worker

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: ??
      #     environment_name: ??
      #     existing_bucket_name: ??
      #     region: ??
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
